-- កសិករទំនើប · Modern Farmer — compost production app (Supabase / Postgres)
--
-- Generated by scripts/gen-sql.mjs from cloud/schema.json.  Do not edit by hand:
-- change the JSON, then run  node scripts/gen-sql.mjs
--
-- How to run: Supabase dashboard -> SQL editor -> paste this whole file -> Run.
-- Re-running is safe (everything is if-not-exists / drop-then-create).
-- Workspace baked into this file: 'plant-01'.

begin;

-- Device-level counters that do not need their own table (lot sequence, operator name).
create table if not exists app_meta (
  id text not null primary key,
  data jsonb not null,
  workspace_id text not null default 'plant-01',
  updated_at timestamptz not null default now()
);
create index if not exists app_meta_workspace_id_idx on app_meta (workspace_id);

create table if not exists materials (
  id text not null,
  name text not null,
  category text not null,
  unit text not null,
  cost_per_unit numeric not null,
  n_pct numeric,
  p_pct numeric,
  k_pct numeric,
  cn_ratio numeric,
  moisture_pct numeric,
  supplier text,
  reorder_qty numeric not null,
  note text,
  archived boolean not null default false,
  created_at date not null,
  workspace_id text not null default 'plant-01',
  updated_at timestamptz not null default now(),
  primary key (id)
);
create index if not exists materials_workspace_id_idx on materials (workspace_id);

create table if not exists material_movements (
  id text not null,
  material_id text not null,
  direction text not null,
  qty numeric not null,
  unit_cost numeric not null,
  reason text not null,
  lot_id text,
  operator text,
  date date not null,
  note text,
  workspace_id text not null default 'plant-01',
  updated_at timestamptz not null default now(),
  primary key (id)
);
create index if not exists material_movements_workspace_id_idx on material_movements (workspace_id);
create index if not exists material_movements_material_id_idx on material_movements (material_id);
create index if not exists material_movements_lot_id_idx on material_movements (lot_id);

create table if not exists recipes (
  id text not null,
  name text not null,
  product_name text not null,
  target_kg numeric not null,
  yield_pct numeric not null,
  fermentation_days integer not null,
  spec jsonb not null,
  lines jsonb not null,
  status text not null,
  note text,
  created_at date not null,
  workspace_id text not null default 'plant-01',
  updated_at timestamptz not null default now(),
  primary key (id)
);
create index if not exists recipes_workspace_id_idx on recipes (workspace_id);

create table if not exists lots (
  id text not null,
  code text not null,
  recipe_id text not null,
  windrow text,
  planned_kg numeric not null,
  actual_kg numeric,
  stage text not null,
  status text not null,
  start_date date not null,
  target_date date not null,
  closed_date date,
  operator text,
  inputs jsonb not null,
  extra_costs jsonb not null,
  note text,
  created_at date not null,
  workspace_id text not null default 'plant-01',
  updated_at timestamptz not null default now(),
  primary key (id)
);
create index if not exists lots_workspace_id_idx on lots (workspace_id);
create index if not exists lots_recipe_id_idx on lots (recipe_id);

create table if not exists process_logs (
  id text not null,
  lot_id text not null,
  date date not null,
  temp_c numeric,
  moisture_pct numeric,
  ph numeric,
  turned boolean not null default false,
  operator text,
  note text,
  workspace_id text not null default 'plant-01',
  updated_at timestamptz not null default now(),
  primary key (id)
);
create index if not exists process_logs_workspace_id_idx on process_logs (workspace_id);
create index if not exists process_logs_lot_id_idx on process_logs (lot_id);

create table if not exists qc_tests (
  id text not null,
  lot_id text not null,
  test_date date not null,
  sample_type text not null,
  om_pct numeric,
  n_pct numeric,
  p_pct numeric,
  k_pct numeric,
  cn_ratio numeric,
  ph numeric,
  moisture_pct numeric,
  ec_ms numeric,
  impurity_pct numeric,
  result text not null,
  grade text,
  tester text,
  note text,
  created_at date not null,
  workspace_id text not null default 'plant-01',
  updated_at timestamptz not null default now(),
  primary key (id)
);
create index if not exists qc_tests_workspace_id_idx on qc_tests (workspace_id);
create index if not exists qc_tests_lot_id_idx on qc_tests (lot_id);

create table if not exists products (
  id text not null,
  name text not null,
  recipe_id text,
  bag_size_kg numeric not null,
  price_per_bag numeric not null,
  price_per_bag_b numeric,
  price_per_bag_c numeric,
  note text,
  created_at date not null,
  workspace_id text not null default 'plant-01',
  updated_at timestamptz not null default now(),
  primary key (id)
);
create index if not exists products_workspace_id_idx on products (workspace_id);
create index if not exists products_recipe_id_idx on products (recipe_id);

create table if not exists product_movements (
  id text not null,
  product_id text not null,
  direction text not null,
  qty_kg numeric not null,
  unit_price numeric not null,
  lot_id text,
  customer_id text,
  party text,
  amount numeric,
  paid numeric,
  payment_method text,
  reason text not null,
  operator text,
  date date not null,
  note text,
  workspace_id text not null default 'plant-01',
  updated_at timestamptz not null default now(),
  primary key (id)
);
create index if not exists product_movements_workspace_id_idx on product_movements (workspace_id);
create index if not exists product_movements_product_id_idx on product_movements (product_id);
create index if not exists product_movements_lot_id_idx on product_movements (lot_id);
create index if not exists product_movements_customer_id_idx on product_movements (customer_id);

create table if not exists customers (
  id text not null,
  name text not null,
  phone text,
  type text not null,
  location text,
  credit_limit numeric,
  note text,
  created_at date not null,
  workspace_id text not null default 'plant-01',
  updated_at timestamptz not null default now(),
  primary key (id)
);
create index if not exists customers_workspace_id_idx on customers (workspace_id);

create table if not exists plans (
  month text not null,
  target_kg numeric not null,
  note text,
  workspace_id text not null default 'plant-01',
  updated_at timestamptz not null default now(),
  primary key (month)
);
create index if not exists plans_workspace_id_idx on plans (workspace_id);

create table if not exists overheads (
  id text not null,
  month text not null,
  category text not null,
  amount numeric not null,
  note text,
  created_at date not null,
  workspace_id text not null default 'plant-01',
  updated_at timestamptz not null default now(),
  primary key (id)
);
create index if not exists overheads_workspace_id_idx on overheads (workspace_id);

-- Row Level Security -----------------------------------------------------------
-- One workspace id ('plant-01') per project: every row carries it, and RLS only ever
-- exposes rows that match it. Change the id by editing cloud/schema.json's consumers or set
-- VITE_SUPABASE_WORKSPACE=<id> before regenerating this file.

-- Per-user role, one row per signed-in account. There is no self-signup in the app, so an
-- admin creates each account (Supabase dashboard -> Authentication -> Users) and then sets
-- their role here once:
--   insert into profiles (id, role) values ('<uuid from auth.users>', 'admin');
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  workspace_id text not null default 'plant-01',
  full_name text,
  role text not null default 'sale' check (role in ('admin','stock','sale')),
  created_at timestamptz not null default now()
);

-- security definer: reads profiles for the *caller* only, bypassing profiles' own RLS
-- (needed so the check below doesn't recurse into the policy it's used by).
create or replace function get_my_role()
returns text
language sql
security definer
set search_path = public
stable
as $$
  select role from profiles where id = auth.uid();
$$;

alter table profiles enable row level security;

drop policy if exists profiles_select on profiles;
create policy profiles_select on profiles for select to authenticated
  using (id = auth.uid() or get_my_role() = 'admin');

drop policy if exists profiles_admin_write on profiles;
create policy profiles_admin_write on profiles for all to authenticated
  using (get_my_role() = 'admin') with check (get_my_role() = 'admin');

alter table materials enable row level security;

-- Requires a signed-in Supabase user. Any authenticated user can read this workspace;
-- writes additionally require the right role (see profiles / get_my_role() above).
drop policy if exists materials_select on materials;
create policy materials_select on materials for select to authenticated
  using (workspace_id = 'plant-01');

drop policy if exists materials_insert on materials;
create policy materials_insert on materials for insert to authenticated
  with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

drop policy if exists materials_update on materials;
create policy materials_update on materials for update to authenticated
  using (workspace_id = 'plant-01') with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

drop policy if exists materials_delete on materials;
create policy materials_delete on materials for delete to authenticated
  using (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

alter table material_movements enable row level security;

-- Requires a signed-in Supabase user. Any authenticated user can read this workspace;
-- writes additionally require the right role (see profiles / get_my_role() above).
drop policy if exists material_movements_select on material_movements;
create policy material_movements_select on material_movements for select to authenticated
  using (workspace_id = 'plant-01');

drop policy if exists material_movements_insert on material_movements;
create policy material_movements_insert on material_movements for insert to authenticated
  with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

drop policy if exists material_movements_update on material_movements;
create policy material_movements_update on material_movements for update to authenticated
  using (workspace_id = 'plant-01') with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

drop policy if exists material_movements_delete on material_movements;
create policy material_movements_delete on material_movements for delete to authenticated
  using (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

alter table recipes enable row level security;

-- Requires a signed-in Supabase user. Any authenticated user can read this workspace;
-- writes additionally require the right role (see profiles / get_my_role() above).
drop policy if exists recipes_select on recipes;
create policy recipes_select on recipes for select to authenticated
  using (workspace_id = 'plant-01');

drop policy if exists recipes_insert on recipes;
create policy recipes_insert on recipes for insert to authenticated
  with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

drop policy if exists recipes_update on recipes;
create policy recipes_update on recipes for update to authenticated
  using (workspace_id = 'plant-01') with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

drop policy if exists recipes_delete on recipes;
create policy recipes_delete on recipes for delete to authenticated
  using (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

alter table lots enable row level security;

-- Requires a signed-in Supabase user. Any authenticated user can read this workspace;
-- writes additionally require the right role (see profiles / get_my_role() above).
drop policy if exists lots_select on lots;
create policy lots_select on lots for select to authenticated
  using (workspace_id = 'plant-01');

drop policy if exists lots_insert on lots;
create policy lots_insert on lots for insert to authenticated
  with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

drop policy if exists lots_update on lots;
create policy lots_update on lots for update to authenticated
  using (workspace_id = 'plant-01') with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

drop policy if exists lots_delete on lots;
create policy lots_delete on lots for delete to authenticated
  using (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

alter table process_logs enable row level security;

-- Requires a signed-in Supabase user. Any authenticated user can read this workspace;
-- writes additionally require the right role (see profiles / get_my_role() above).
drop policy if exists process_logs_select on process_logs;
create policy process_logs_select on process_logs for select to authenticated
  using (workspace_id = 'plant-01');

drop policy if exists process_logs_insert on process_logs;
create policy process_logs_insert on process_logs for insert to authenticated
  with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

drop policy if exists process_logs_update on process_logs;
create policy process_logs_update on process_logs for update to authenticated
  using (workspace_id = 'plant-01') with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

drop policy if exists process_logs_delete on process_logs;
create policy process_logs_delete on process_logs for delete to authenticated
  using (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

alter table qc_tests enable row level security;

-- Requires a signed-in Supabase user. Any authenticated user can read this workspace;
-- writes additionally require the right role (see profiles / get_my_role() above).
drop policy if exists qc_tests_select on qc_tests;
create policy qc_tests_select on qc_tests for select to authenticated
  using (workspace_id = 'plant-01');

drop policy if exists qc_tests_insert on qc_tests;
create policy qc_tests_insert on qc_tests for insert to authenticated
  with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

drop policy if exists qc_tests_update on qc_tests;
create policy qc_tests_update on qc_tests for update to authenticated
  using (workspace_id = 'plant-01') with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

drop policy if exists qc_tests_delete on qc_tests;
create policy qc_tests_delete on qc_tests for delete to authenticated
  using (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

alter table products enable row level security;

-- Requires a signed-in Supabase user. Any authenticated user can read this workspace;
-- writes additionally require the right role (see profiles / get_my_role() above).
drop policy if exists products_select on products;
create policy products_select on products for select to authenticated
  using (workspace_id = 'plant-01');

drop policy if exists products_insert on products;
create policy products_insert on products for insert to authenticated
  with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock', 'sale'));

drop policy if exists products_update on products;
create policy products_update on products for update to authenticated
  using (workspace_id = 'plant-01') with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock', 'sale'));

drop policy if exists products_delete on products;
create policy products_delete on products for delete to authenticated
  using (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock', 'sale'));

alter table product_movements enable row level security;

-- Requires a signed-in Supabase user. Any authenticated user can read this workspace;
-- writes additionally require the right role (see profiles / get_my_role() above).
drop policy if exists product_movements_select on product_movements;
create policy product_movements_select on product_movements for select to authenticated
  using (workspace_id = 'plant-01');

drop policy if exists product_movements_insert on product_movements;
create policy product_movements_insert on product_movements for insert to authenticated
  with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock', 'sale'));

drop policy if exists product_movements_update on product_movements;
create policy product_movements_update on product_movements for update to authenticated
  using (workspace_id = 'plant-01') with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock', 'sale'));

drop policy if exists product_movements_delete on product_movements;
create policy product_movements_delete on product_movements for delete to authenticated
  using (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock', 'sale'));

alter table customers enable row level security;

-- Requires a signed-in Supabase user. Any authenticated user can read this workspace;
-- writes additionally require the right role (see profiles / get_my_role() above).
drop policy if exists customers_select on customers;
create policy customers_select on customers for select to authenticated
  using (workspace_id = 'plant-01');

drop policy if exists customers_insert on customers;
create policy customers_insert on customers for insert to authenticated
  with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'sale'));

drop policy if exists customers_update on customers;
create policy customers_update on customers for update to authenticated
  using (workspace_id = 'plant-01') with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'sale'));

drop policy if exists customers_delete on customers;
create policy customers_delete on customers for delete to authenticated
  using (workspace_id = 'plant-01' and get_my_role() in ('admin', 'sale'));

alter table plans enable row level security;

-- Requires a signed-in Supabase user. Any authenticated user can read this workspace;
-- writes additionally require the right role (see profiles / get_my_role() above).
drop policy if exists plans_select on plans;
create policy plans_select on plans for select to authenticated
  using (workspace_id = 'plant-01');

drop policy if exists plans_insert on plans;
create policy plans_insert on plans for insert to authenticated
  with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

drop policy if exists plans_update on plans;
create policy plans_update on plans for update to authenticated
  using (workspace_id = 'plant-01') with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

drop policy if exists plans_delete on plans;
create policy plans_delete on plans for delete to authenticated
  using (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

alter table overheads enable row level security;

-- Requires a signed-in Supabase user. Any authenticated user can read this workspace;
-- writes additionally require the right role (see profiles / get_my_role() above).
drop policy if exists overheads_select on overheads;
create policy overheads_select on overheads for select to authenticated
  using (workspace_id = 'plant-01');

drop policy if exists overheads_insert on overheads;
create policy overheads_insert on overheads for insert to authenticated
  with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

drop policy if exists overheads_update on overheads;
create policy overheads_update on overheads for update to authenticated
  using (workspace_id = 'plant-01') with check (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

drop policy if exists overheads_delete on overheads;
create policy overheads_delete on overheads for delete to authenticated
  using (workspace_id = 'plant-01' and get_my_role() in ('admin', 'stock'));

alter table app_meta enable row level security;

-- Requires a signed-in Supabase user. Any authenticated user can read this workspace;
-- writes additionally require the right role (see profiles / get_my_role() above).
drop policy if exists app_meta_select on app_meta;
create policy app_meta_select on app_meta for select to authenticated
  using (workspace_id = 'plant-01');

drop policy if exists app_meta_insert on app_meta;
create policy app_meta_insert on app_meta for insert to authenticated
  with check (workspace_id = 'plant-01');

drop policy if exists app_meta_update on app_meta;
create policy app_meta_update on app_meta for update to authenticated
  using (workspace_id = 'plant-01') with check (workspace_id = 'plant-01');

drop policy if exists app_meta_delete on app_meta;
create policy app_meta_delete on app_meta for delete to authenticated
  using (workspace_id = 'plant-01');

commit;

-- Quick checks after running:
--   select table_name from information_schema.tables where table_schema='public' order by 1;
--   select count(*) from lots;
