#!/usr/bin/env node
/**
 * Generates supabase/schema.sql from cloud/schema.json — the same definition the browser
 * sync layer uses — so the SQL you run in Supabase can never disagree with the columns
 * the app writes.
 *
 *   node scripts/gen-sql.mjs          # rewritten supabase/schema.sql
 *   node scripts/gen-sql.mjs --check  # fail if the committed file is stale
 */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import path from "node:path";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");

const schema = JSON.parse(await readFile(path.join(root, "cloud/schema.json"), "utf8"));
const WS = schema.workspaceColumn;
// A single shared workspace per project keeps the browser app usable with the anon key;
// set WORKSPACE_ID below (env or constant) and it is baked into both the default and the policy.
const WORKSPACE = process.env.VITE_SUPABASE_WORKSPACE || "plant-01";

const pkColumn = (t) => t.columns.find((c) => c.field === t.pk).column;
const sqlType = (t) =>
  ({ numeric: "numeric", integer: "integer", boolean: "boolean", jsonb: "jsonb", date: "date" })[
    t.type
  ] ?? "text";

function tableSql(t) {
  const cols = t.columns.map(
    (c) =>
      `  ${c.column} ${sqlType(c)}${c.nullable ? "" : " not null"}${
        c.default ? ` default ${c.default}` : ""
      }`,
  );
  cols.push(`  ${WS} text not null default '${WORKSPACE}'`);
  cols.push(`  updated_at timestamptz not null default now()`);
  const out = [
    `create table if not exists ${t.table} (`,
    cols.join(",\n") + ",",
    `  primary key (${pkColumn(t)})`,
    `);`,
    `create index if not exists ${t.table}_${WS}_idx on ${t.table} (${WS});`,
  ];
  t.columns
    .filter((c) => c.column.endsWith("_id") && c.column !== pkColumn(t))
    .forEach((c) =>
      out.push(`create index if not exists ${t.table}_${c.column}_idx on ${t.table} (${c.column});`),
    );
  return out.join("\n");
}

function policySql(table, writeRoles) {
  const roleCheck = writeRoles && writeRoles.length
    ? ` and get_my_role() in (${writeRoles.map((r) => `'${r}'`).join(", ")})`
    : "";
  return `alter table ${table} enable row level security;

-- Requires a signed-in Supabase user. Any authenticated user can read this workspace;
-- writes additionally require the right role (see profiles / get_my_role() above).
drop policy if exists ${table}_select on ${table};
create policy ${table}_select on ${table} for select to authenticated
  using (${WS} = '${WORKSPACE}');

drop policy if exists ${table}_insert on ${table};
create policy ${table}_insert on ${table} for insert to authenticated
  with check (${WS} = '${WORKSPACE}'${roleCheck});

drop policy if exists ${table}_update on ${table};
create policy ${table}_update on ${table} for update to authenticated
  using (${WS} = '${WORKSPACE}') with check (${WS} = '${WORKSPACE}'${roleCheck});

drop policy if exists ${table}_delete on ${table};
create policy ${table}_delete on ${table} for delete to authenticated
  using (${WS} = '${WORKSPACE}'${roleCheck});`;
}

const allTables = [...schema.tables.map((t) => t.table), schema.metaTable];
const writeRolesOf = (table) => schema.tables.find((t) => t.table === table)?.writeRoles;

const sql = `-- កសិករទំនើប · Modern Farmer — compost production app (Supabase / Postgres)
--
-- Generated by scripts/gen-sql.mjs from cloud/schema.json.  Do not edit by hand:
-- change the JSON, then run  node scripts/gen-sql.mjs
--
-- How to run: Supabase dashboard -> SQL editor -> paste this whole file -> Run.
-- Re-running is safe (everything is if-not-exists / drop-then-create).
-- Workspace baked into this file: '${WORKSPACE}'.

begin;

-- Device-level counters that do not need their own table (lot sequence, operator name).
create table if not exists ${schema.metaTable} (
  id text not null primary key,
  data jsonb not null,
  ${WS} text not null default '${WORKSPACE}',
  updated_at timestamptz not null default now()
);
create index if not exists ${schema.metaTable}_${WS}_idx on ${schema.metaTable} (${WS});

${schema.tables.map(tableSql).join("\n\n")}

-- Row Level Security -----------------------------------------------------------
-- One workspace id ('${WORKSPACE}') per project: every row carries it, and RLS only ever
-- exposes rows that match it. Change the id by editing cloud/schema.json's consumers or set
-- VITE_SUPABASE_WORKSPACE=<id> before regenerating this file.

-- Per-user role, one row per signed-in account. There is no self-signup in the app, so an
-- admin creates each account (Supabase dashboard -> Authentication -> Users) and then sets
-- their role here once:
--   insert into profiles (id, role) values ('<uuid from auth.users>', 'admin');
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  ${WS} text not null default '${WORKSPACE}',
  full_name text,
  role text not null default 'sale' check (role in ('admin','stock','sale')),
  created_at timestamptz not null default now()
);

-- security definer: reads profiles for the *caller* only, bypassing profiles' own RLS
-- (needed so the check below doesn't recurse into the policy it's used by).
create or replace function get_my_role()
returns text
language sql
security definer
set search_path = public
stable
as $$
  select role from profiles where id = auth.uid();
$$;

alter table profiles enable row level security;

drop policy if exists profiles_select on profiles;
create policy profiles_select on profiles for select to authenticated
  using (id = auth.uid() or get_my_role() = 'admin');

drop policy if exists profiles_admin_write on profiles;
create policy profiles_admin_write on profiles for all to authenticated
  using (get_my_role() = 'admin') with check (get_my_role() = 'admin');

${allTables.map((t) => policySql(t, writeRolesOf(t))).join("\n\n")}

commit;

-- Quick checks after running:
--   select table_name from information_schema.tables where table_schema='public' order by 1;
--   select count(*) from lots;
`;

const tsTarget = path.join(root, "src/lib/schema.generated.ts");
const tsBody = `/** Generated from cloud/schema.json by scripts/gen-sql.mjs — do not edit. */
import type { SchemaDoc } from "./schemaTypes";

export const schema = ${JSON.stringify(schema, null, 2)} as const satisfies SchemaDoc;
`;

const target = path.join(root, "supabase/schema.sql");
if (process.argv.includes("--stdout")) {
  process.stdout.write(sql);
} else if (check) {
  const existing = await readFile(target, "utf8").catch(() => "");
  const existingTs = await readFile(tsTarget, "utf8").catch(() => "");
  if (existing !== sql || existingTs !== tsBody) {
    console.error("generated files are stale — run: node scripts/gen-sql.mjs");
    process.exit(1);
  }
  console.log("OK schema.sql + schema.generated.ts match cloud/schema.json");
} else {
  await writeFile(target, sql);
  await writeFile(tsTarget, tsBody);
  console.log(`wrote supabase/schema.sql + src/lib/schema.generated.ts (${schema.tables.length} tables + ${schema.metaTable})`);
}
